import time
import logging
from typing import List
from google import genai
from google.genai import types
from app.config import GEMINI_API_KEY, GEMINI_MODEL
from app.models.schemas import SourceItem

logger = logging.getLogger(__name__)

RAG_PROMPT_TEMPLATE = """You are a helpful, professional AI Document Assistant.
Answer the user's question accurately and concisely using ONLY the provided document context chunks below.
If the context does not contain sufficient information to answer the question, state clearly that the answer is not available in the indexed documents.

=== DOCUMENT CONTEXT ===
{context_text}
========================

USER QUESTION: {question}

INSTRUCTIONS:
1. Provide a comprehensive, accurate answer based strictly on the document context provided above.
2. Structure your answer using clear Markdown headings, bullet points, and code blocks where appropriate.
3. If referencing specific parts, mention the source document name.
"""

class LLMService:
    def __init__(self):
        self.api_key = GEMINI_API_KEY
        self.client = None
        if self.api_key and self.api_key != "your_gemini_api_key_here":
            try:
                self.client = genai.Client(api_key=self.api_key)
            except Exception as e:
                logger.error(f"Failed to initialize Google GenAI client: {e}")

    def generate_rag_answer(self, question: str, sources: List[SourceItem]) -> tuple[str, float]:
        start_time = time.time()

        if not sources:
            elapsed = (time.time() - start_time) * 1000
            return (
                "No relevant document content was found to answer your question. "
                "Please upload documents or refine your question.",
                elapsed
            )

        # Build context block
        context_parts = []
        for idx, source in enumerate(sources, 1):
            context_parts.append(
                f"[Source {idx}: {source.source} (Chunk {source.chunk_index}, Score: {source.score:.2f})]\n"
                f"{source.snippet}\n"
            )
        context_text = "\n".join(context_parts)

        prompt = RAG_PROMPT_TEMPLATE.format(context_text=context_text, question=question)

        # Check API key configuration
        if not self.api_key or self.api_key == "your_gemini_api_key_here":
            elapsed = (time.time() - start_time) * 1000
            return (
                "⚠️ **Gemini API Key missing or unconfigured.**\n\n"
                "Please set a valid `GEMINI_API_KEY` in the `backend/.env` file to generate AI answers.\n\n"
                "### Retrieved Document Chunks:\n\n" + context_text,
                elapsed
            )

        try:
            if not self.client:
                self.client = genai.Client(api_key=self.api_key)

            response = self.client.models.generate_content(
                model=GEMINI_MODEL,
                contents=prompt,
                config=types.GenerateContentConfig(
                    temperature=0.2,
                    top_p=0.95,
                    max_output_tokens=2048,
                )
            )

            answer = response.text if response and response.text else "No response generated by Gemini."
            elapsed = (time.time() - start_time) * 1000
            return answer, elapsed

        except Exception as e:
            logger.error(f"Gemini API generation error: {e}")
            elapsed = (time.time() - start_time) * 1000
            error_msg = str(e)
            if "quota" in error_msg.lower():
                return (
                    "⚠️ **Gemini API Quota Exceeded.** Please check your Google Gemini API quota or try again shortly.",
                    elapsed
                )
            elif "invalid" in error_msg.lower() or "api_key" in error_msg.lower():
                return (
                    "⚠️ **Invalid Gemini API Key.** Please verify your `GEMINI_API_KEY` in `backend/.env`.",
                    elapsed
                )
            else:
                return (
                    f"⚠️ **Error generating answer with Gemini**: {error_msg}\n\n"
                    "### Retrieved Context:\n" + context_text,
                    elapsed
                )

llm_service = LLMService()
